In [6]:
import pandas as pd
import numpy as np

l = [[1,2,3,4],[4,5,6,7],[9,7,8,6]]
a = np.array(l)
print(a,id(a),type(a))
print(a.shape)
print("="*20)

s = pd.Series(l)          # Here, Series() will not accept "a" array cause a is a 2D array. So Series() always need 1D object as a parameter
print(s,id(s),type(s))
print(s.shape)
print("="*20)

p = pd.DataFrame(a)
print(p,id(p),type(p))
print(p.shape)

[[1 2 3 4]
 [4 5 6 7]
 [9 7 8 6]] 2137179743280 <class 'numpy.ndarray'>
(3, 4)
0    [1, 2, 3, 4]
1    [4, 5, 6, 7]
2    [9, 7, 8, 6]
dtype: object 2137180004304 <class 'pandas.core.series.Series'>
(3,)
   0  1  2  3
0  1  2  3  4
1  4  5  6  7
2  9  7  8  6 2137206648400 <class 'pandas.core.frame.DataFrame'>
(3, 4)


In [8]:
import pandas as pd
import numpy as np

dict = {'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,8,7,6]}
print(dict)
a = np.array(dict)  # This does not work cause we can't convert dictionaries into ndarrays
print(a,type(a))
print(a.shape)
print("="*20)

s = pd.Series(dict)
print(s)
print(s.shape,s.ndim)
print("="*20)

# d = pd.DataFrame(a) ---> Here, DataFrame() accepts only 2D objects as parameter. So, it will not accept 'a' array cause 'a' doesn't have any dimensions
d = pd.DataFrame(dict)
print(d)
print(d.shape,d.ndim)

"""While working with dictionaries in pandas,
 - The keys in dict became index(row) names for Series(), the values in dict became data(column) for Series().
 - The keys in dict became column names for DataFrame(), the values in dict became rows(data) for DataFrame().
 - The row names for Series() became column names in DataFrame that's why the shape of Series obj and DataFrame obj get different
    in above ex. s.shape = (3,) & d.shape = (4,3) , So number of Series rows = number of DataFrame Columns"""


{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 8, 7, 6]}
{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 8, 7, 6]} <class 'numpy.ndarray'>
()
a    [1, 2, 3, 4]
b    [5, 6, 7, 8]
c    [9, 8, 7, 6]
dtype: object
(3,) 1
   a  b  c
0  1  5  9
1  2  6  8
2  3  7  7
3  4  8  6
(4, 3) 2


"While working with dictionaries in pandas,\n - The keys in dict became index(row) names for Series(), the values in dict became data(column) for Series().\n - The keys in dict became column names for DataFrame(), the values in dict became rows(data) for DataFrame().\n - The row names for Series() became column names in DataFrame that's why the shape of Series obj and DataFrame obj get different\n    in above ex. s.shape = (3,) & d.shape = (4,3) , So number of Series rows = number of DataFrame Columns"